# Generated by Django 4.2.30 on 2026-04-16 12:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_address', models.TextField(blank=True, help_text='Endereço de partida/origem')),
                ('origin_lat', models.FloatField(blank=True, null=True)),
                ('origin_lng', models.FloatField(blank=True, null=True)),
                ('fuel_consumption', models.FloatField(default=10.0, help_text='Consumo médio em km/l')),
                ('fuel_price', models.FloatField(default=6.5, help_text='Preço do litro de combustível em R$')),
                ('total_distance_m', models.FloatField(blank=True, help_text='Distância total em metros', null=True)),
                ('total_duration_s', models.FloatField(blank=True, help_text='Tempo estimado em segundos', null=True)),
                ('is_optimized', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Sessão de Rota',
                'verbose_name_plural': 'Sessões de Rota',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Ordem na rota otimizada')),
                ('address', models.TextField(help_text='Endereço original informado')),
                ('formatted_address', models.TextField(blank=True, help_text='Endereço formatado pela API')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('geocoded', models.BooleanField(default=False)),
                ('geocode_error', models.TextField(blank=True)),
                ('distance_to_next_m', models.FloatField(blank=True, null=True)),
                ('duration_to_next_s', models.FloatField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='routes.routesession')),
            ],
            options={
                'verbose_name': 'Ponto da Rota',
                'verbose_name_plural': 'Pontos da Rota',
                'ordering': ['order'],
            },
        ),
    ]
